### ISSUE TITLE
แจ้ง Error Function ThaiCovid19()

### ISSUE THREAD

**Issue by ktanan** [UncleEngineer/covid19#5]
สวัสดีครับ 
แจ้ง Error Function ThaiCovid19()
----------------------------------
D:\SourcePython\test1>covid19.py
Traceback (most recent call last):
  File "D:\SourcePython\test1\covid19.py", line 14, in <module>
    thai = ThaiCovid19()
  File "C:\Users\P2506039\AppData\Local\Programs\Python\Python37\lib\site-packages\covid19uncle\covid19.py", line 110, in ThaiCovid19
    result['รักษาพยาบาลสังเกตอาการ'] = alldata[11][2]
IndexError: list index out of range
--------------
ปล.ผมมือใหม่เพิ่งหัดเขียน Python ครับ

**Comment by sirilerklab** [comment]
Update ครับ

pip install covid19uncle==0.0.2

**Comment by korrio** [comment]
แจ้ง error เพิ่มเติม 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/covid19uncle/covid19.py", line 104, in ThaiCovid19
    result['ผู้ป่วยกลับบ้านแล้ว'] = alldata[5][2]
IndexError: list index out of range
```
workaround: comment line 104
#result['ผู้ป่วยกลับบ้านแล้ว'] = alldata[5][2]

**Comment by korrio** [comment]
คำแนะนำ 
เนื่องจาก html เปลี่ยนบ่อยเลยอยากให้เช็ค null/undefined ก่อนอัดเข้า array ครับ
